name: "build-frontend"

on:
  push:
    branches: [ main ]

defaults:
  run:
    working-directory: frontend

jobs:
  # vue build
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: |
        npm i
    - name: Running Vue Build
      run: |
        npm run build
